repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: ''
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--extend-select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
